spring:
  application:
    name: mybatis-mul-datasource
  jackson:
          serialization.indent_output: true
  profiles:
    active: @spring.profiles.active@
    include: swagger
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://{0}:3306/{1}?useUnicode=true&characterEncoding=utf8&useSSL=false&rewriteBatchedStatements=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    validation-query: SELECT 1
    time-between-eviction-runs-millis: 600000
    min-evictable-idle-time-millis: 1800000
    maximum-pool-size: 80

server:
  port: 8902
  tomcat:
    basedir: /tomcat/tmp
